name: 'Notify Orchestrator'
description: 'Send deployment status notification to Mana orchestrator'

inputs:
  deployment-id:
    description: 'Deployment ID'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: true
  version:
    description: 'Application version'
    required: true
  status:
    description: 'Deployment status (in_progress/success/failed)'
    required: true
  failure-type:
    description: 'Failure type if status is failed'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Send notification
      shell: bash
      env:
        ORCHESTRATOR_URL: ${{ secrets.ORCHESTRATOR_URL }}
      run: |
        if [ -z "$ORCHESTRATOR_URL" ]; then
          echo "⚠️  Orchestrator URL not configured, skipping notification"
          exit 0
        fi
        
        PAYLOAD=$(cat <<EOF
        {
          "deployment_id": "${{ inputs.deployment-id }}",
          "namespace": "${{ inputs.namespace }}",
          "app_name": "sample-app",
          "version": "${{ inputs.version }}",
          "status": "${{ inputs.status }}",
          "failure_type": "${{ inputs.failure-type }}",
          "metadata": {
            "commit": "${{ github.sha }}",
            "author": "${{ github.actor }}",
            "branch": "${{ github.ref_name }}",
            "workflow_run_id": "${{ github.run_id }}",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          }
        }
        EOF
        )
        
        echo "Sending notification to orchestrator..."
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
          -X POST "$ORCHESTRATOR_URL/webhook/deployment" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD")
        
        if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
          echo "✓ Notification sent successfully (HTTP $HTTP_CODE)"
        else
          echo "⚠️  Notification failed (HTTP $HTTP_CODE)"
          echo "This is expected if orchestrator is not yet deployed"
        fi